import { Inter } from "next/font/google";
// import "./globals.css";使うときにコメントアウトを外す

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
// export const viewport = {
//   width: "device-width",
//   initialScale: 1,
//   maximumScale: 1,
//   userScalable: 1,
//   // Also supported by less commonly used
//   // interactiveWidget: 'resizes-visual',
// };
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
